# Generated by Django 5.0.6 on 2024-06-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbookingg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmodel',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='ownermodel',
            name='hotels',
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ownermodel',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='ownermodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ownermodel',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='rent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='room_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelmodel',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='hotelbookingg.ownermodel'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotelbookingg.hotelmodel'),
        ),
    ]
